---
apiVersion: v1
kind: Service
metadata:
  name: dataarchive-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080   # Minikube accessible on this port
